
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjRlMzMxLWM0NGItNGZhMi04ZDU4LTVmZjQ1ZjkyM2ExNCIsImVtYWlsIjoidmljdG9yQHlhLnJ1IiwibmFtZSI6IlZpY3RvciIsInJvbGVzIjpbIkdVRVNUIiwiVVNFUiJdLCJpc0FjdGl2YXRlZCI6dHJ1ZSwiaWF0IjoxNjcwMzI4NjcwLCJleHAiOjE2NzAzMzA0NzB9.s3bRGt9Jp4FxpZByEDoeVX__6GuQ8guAUI2kpQDTUB0